# site settings
title: BibleBot
subtitle: by Evangelion Ltd.
email: legal@evangelion.uk
description: The premier Discord bot for Bible verses and Christian resources.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://biblebot.xyz" # the base hostname & protocol for your site
author:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/BibleBot
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

excerpt_separator: <!--more-->
permalink: /blog/:title/

plugins:
  - jekyll-feed
